### ISSUE TITLE
Laravel 10 upgrade?

### ISSUE THREAD

**Issue by zanstro** [NilGems/laravel-textract#5]
Hello,

First of all, I would like to thank you for your work on this great package. 

I was wondering if you are planning to upgrade the compatibility with Laravel 10. 

p.s.: is the PowerPoint compatibility still on the roadmap?

Thank you in advance.

**Comment by returnmk** [comment]
Hello, I am truly interested in this one too, especially the PowerPoint compatibility.

Keep up the good work mate!

**Comment by oliverbj** [comment]
Interested in this as well!

**Comment by NilGems** [comment]
I am working quickly to add support for Laravel 10. I apologize deeply for the wait, but maintaining the code is quite challenging with a busy schedule.

I sincerely appreciate your interest.
